<?php
/**
 * Custom landing page.
 *
 * @package CodesBlock
 */

get_header( 'landing' );
?>

<main>
<section class="hero">
  <div class="wrap hero-grid">
    <div>
      <div class="eyebrow">System Design · AI-native · Interview practice</div>
      <h1>Crack the <span>System Design</span> Interview.</h1>
      <p class="lead">Learn to design scalable systems from first principles, explain the trade-offs behind them, and extend the same thinking to <strong>RAG, vector search, AI gateways, agents and realtime voice.</strong></p>
      <p class="promise">Learn the systems interviewers have always asked—and the ones they're beginning to ask now.</p>
      <div class="hero-cta"><a class="btn primary btn-lg" href="#start">Start learning free →</a><a class="btn btn-lg" href="#curriculum">Explore curriculum</a></div>
      <div class="micro"><span><i class="tick">✓</i>No card required</span><span><i class="tick">✓</i>Voice AI tutor</span><span><i class="tick">✓</i>Architecture labs</span><span><i class="tick">✓</i>AI mock interviews</span></div>
      <div class="hero-stats"><div><b>90+ lessons</b><span>from fundamentals to AI systems</span></div><div><b>18 design labs</b><span>classic + modern architectures</span></div><div><b>8 mock interviews</b><span>constraint-changing practice</span></div><div><b>1 method</b><span>clarify → design → break → defend</span></div></div>
    </div>

    <div class="course-window" aria-label="Course learning experience preview">
      <div class="windowtop"><i></i><i></i><i></i><small>Lesson 42 · AI gateway & model routing</small></div>
      <div class="demo">
        <div class="lesson"><small>Why direct model calls fail at scale</small><h3>Your checkout service should not depend directly on one model provider.</h3><p>At small scale, <span class="highlight">Backend → Model API</span> looks fine. In production it creates a single point of failure, inconsistent policy enforcement, weak cost visibility and provider lock-in.</p><div class="toolrow"><span class="tool on">Ask AI</span><span class="tool">Explain trade-off</span><span class="tool">Bookmark</span></div><div class="arch"><div class="flow"><span class="node">Service</span><span class="arrow">→</span><span class="node ai">AI Gateway</span><span class="arrow">→</span><span class="node">Router</span><span class="arrow">→</span><span class="node">Model A</span><span class="node">Model B</span></div></div><p class="tiny" style="margin-top:12px">Interview follow-up: What changes when p99 model latency rises from 800 ms to 8 s?</p></div>
        <aside class="tutor"><div class="tutor-head"><span><i class="orb"></i>AI Tutor</span><span class="voice-tag">Voice ready</span></div><div class="chat"><small>Selected from lesson</small><p>“Backend → Model API creates a single point of failure.”</p></div><div class="chat"><small>Tutor</small><p>Think of the model like any external dependency—but slower, more expensive and less deterministic. Add routing, timeouts, fallbacks, observability and cost controls before it becomes critical-path infrastructure.</p></div><div class="wave"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><div class="talk">● Talk to your tutor</div></aside>
      </div>
    </div>
  </div>
  <div class="wrap anchor"><div class="anchor-inner"><a href="#difference">Why this course</a><a href="#method">How you'll learn</a><a href="#ai-era">AI system design</a><a href="#curriculum">Curriculum</a><a href="#labs">Design labs</a><a href="#tutor">AI tutor</a></div></div>
</section>

<section class="surface" id="difference">
  <div class="wrap">
    <div class="section-head"><div class="kicker">The course thesis</div><h2>The old stack is not disappearing. <span class="accent">It is getting a new layer.</span></h2><p>Strong AI products still need APIs, databases, caching, queues, security, reliability and observability. Modern engineers also need to reason about retrieval quality, token cost, model latency, tool execution and probabilistic failure.</p></div>
    <div class="split-story">
      <article class="story-card"><div class="label">The stack you already know</div><h3>Traditional distributed systems</h3><div class="stack"><span>APIs</span><span>Load Balancers</span><span>Redis</span><span>Kafka</span><span>SQL / NoSQL</span><span>CDN</span><span>Queues</span><span>Microservices</span><span>Observability</span></div></article>
      <article class="story-card dark"><div class="label">The layer appearing on top</div><h3>AI-native production systems</h3><div class="stack"><span>LLM Gateway</span><span>Embeddings</span><span>Vector Search</span><span>RAG</span><span>Reranking</span><span>Agents</span><span>MCP</span><span>Evals</span><span>Realtime Voice</span></div></article>
      <div class="bridge"><blockquote>“I already know APIs, databases, Redis, Kafka and microservices. <span>What changes</span> when my application has an LLM, RAG pipeline, vector search, AI agent or voice model in the architecture?”</blockquote><p>That question is the bridge this course is built around. You learn traditional system design deeply first, then reuse those mental models when AI makes latency variable, output probabilistic, context stateful and each request materially expensive.</p></div>
    </div>
  </div>
</section>

<section id="method">
  <div class="wrap">
    <div class="section-head center"><div class="kicker">CodesBlock method</div><h2>Most courses show the diagram. You learn to <span class="accent">arrive at it.</span></h2><p>Every design problem follows the same reasoning loop until it becomes automatic under interview pressure.</p></div>
    <div class="compare"><div class="col"><div class="n">01</div><strong>S</strong><b>Scope</b><p>Clarify users, requirements, constraints and what is explicitly out of scope.</p></div><div class="col"><div class="n">02</div><strong>C</strong><b>Calculate</b><p>Estimate QPS, storage, bandwidth, latency and cost before choosing components.</p></div><div class="col"><div class="n">03</div><strong>A</strong><b>Architect</b><p>Draw APIs, data flow, services, storage and the system's critical path.</p></div><div class="col"><div class="n">04</div><strong>L</strong><b>Load-test</b><p>Break the design with hotspots, failures, retries, scale and bad assumptions.</p></div><div class="col"><div class="n">05</div><strong>E</strong><b>Explain</b><p>Defend trade-offs, alternatives and what you would change at 10× scale.</p></div></div>
  </div>
</section>

<section class="surface">
  <div class="wrap method-grid">
    <article class="method-card"><div class="kicker">Architecture evolves</div><h3>Start simple. Add complexity only when a requirement forces it.</h3><p>You should be able to explain why every box exists. The course repeatedly starts from a naive design and lets constraints force the next architectural decision.</p><div class="evolve"><div class="evolve-row"><small>v1</small><div class="evolve-path"><span>Client</span><span>→</span><span>Server</span><span>→</span><span>Database</span></div></div><div class="evolve-row"><small>scale</small><div class="evolve-path"><span>Client</span><span>→</span><span>LB</span><span>→</span><span>Services</span><span>→</span><span>Cache</span><span>→</span><span>DB</span></div></div><div class="evolve-row"><small>ai layer</small><div class="evolve-path"><span>Services</span><span>→</span><span class="new">AI Gateway</span><span>→</span><span class="new">RAG / Tools</span><span>→</span><span class="new">Models</span></div></div></div></article>
    <article class="method-card pressure"><div class="kicker" style="color:#8ec0ff">Pressure testing</div><h3>Your first answer is only the beginning.</h3><p>The AI interviewer keeps changing one constraint so you practise adapting instead of memorizing finished solutions.</p><div class="question"><small>Interviewer</small><p>“Your architecture works. Now one customer has 80 million followers. What breaks first?”</p></div><div class="question"><small>Then</small><p>“Now the model provider is degraded and p99 latency is 12 seconds. Keep the core product usable.”</p></div><div class="score"><div class="score-row"><span>Scalability</span><i><span style="width:84%"></span></i><b>8.4</b></div><div class="score-row"><span>Reliability</span><i><span style="width:62%"></span></i><b>6.2</b></div><div class="score-row"><span>Cost</span><i><span style="width:48%"></span></i><b>4.8</b></div></div></article>
  </div>
</section>

<section class="ai-era" id="ai-era">
  <div class="wrap">
    <div class="section-head"><div class="kicker">Modern system design</div><h2>What changes when the dependency becomes <span style="color:#8ec0ff">intelligent?</span></h2><p>The course treats AI as architecture, not magic. Each topic connects back to concepts backend engineers already understand: APIs, queues, caching, state, failure isolation, access control, cost and observability.</p></div>
    <div class="ai-grid">
      <article class="ai-card"><span class="tag">RAG</span><h3>Retrieval systems</h3><p>Ingestion, chunking, embeddings, vector indexes, hybrid search, reranking, freshness, permissions and context assembly.</p><div class="mini-flow"><span>Docs</span><i>→</i><span>Embed</span><i>→</i><span>Retrieve</span><i>→</i><span>Rerank</span><i>→</i><span>LLM</span></div></article>
      <article class="ai-card"><span class="tag">GATEWAY</span><h3>Model routing & reliability</h3><p>Centralize policy, rate limits, provider routing, fallbacks, streaming, semantic caching, token budgets and model outages.</p><div class="mini-flow"><span>App</span><i>→</i><span>Gateway</span><i>→</i><span>Router</span><i>→</i><span>Models</span></div></article>
      <article class="ai-card"><span class="tag">AGENTS</span><h3>Agents meet microservices</h3><p>Tool schemas, agent state, durable jobs, permissions, idempotent actions, human approval, MCP and bounded autonomy.</p><div class="mini-flow"><span>Agent</span><i>→</i><span>Tools</span><i>→</i><span>Services</span><i>↺</i><span>State</span></div></article>
      <article class="ai-card"><span class="tag">EVALS</span><h3>Quality becomes observable</h3><p>Golden datasets, retrieval metrics, traces, regressions, online feedback, human review and evaluation gates.</p><div class="mini-flow"><span>Trace</span><i>→</i><span>Eval</span><i>→</i><span>Score</span><i>→</i><span>Release</span></div></article>
      <article class="ai-card"><span class="tag">SECURITY</span><h3>New failure surfaces</h3><p>Prompt injection, poisoned retrieval, data leakage, tool abuse, excessive agency and authorization boundaries.</p><div class="mini-flow"><span>Input</span><i>→</i><span>Policy</span><i>→</i><span>Tool</span><i>→</i><span>Verify</span></div></article>
      <article class="ai-card"><span class="tag">VOICE</span><h3>Realtime AI</h3><p>WebRTC, streaming audio, speech pipelines, barge-in, session state, tool calls and end-to-end latency budgets.</p><div class="mini-flow"><span>Audio</span><i>→</i><span>Model</span><i>→</i><span>Tools</span><i>→</i><span>Audio</span></div></article>
    </div>
  </div>
</section>

<section id="curriculum">
  <div class="wrap">
    <div class="section-head"><div class="kicker">Full learning path</div><h2>From a single server to <span class="accent">production AI architecture.</span></h2><p>One progression instead of two disconnected courses. Open a phase to see the material.</p></div>
    <div class="curriculum-layout">
      <div class="phases">
        <details class="phase" open><summary><span class="phase-no">01</span><span class="phase-title"><b>Think like a system designer</b><span>interview structure · requirements · estimation · APIs · trade-offs</span></span></summary><div class="phase-content"><p>Build the interview operating system before memorizing architecture.</p><div class="topic-grid"><span class="topic">What system design interviews actually test</span><span class="topic">Functional vs non-functional requirements</span><span class="topic">QPS, storage, bandwidth and latency estimates</span><span class="topic">API contracts and core entities</span><span class="topic">Critical-path thinking</span><span class="topic">SCALE-45 framework</span></div></div></details>
        <details class="phase"><summary><span class="phase-no">02</span><span class="phase-title"><b>Scale — from one server to millions</b><span>networking · load balancing · caching · databases · queues</span></span></summary><div class="phase-content"><p>Learn each building block as an answer to a specific bottleneck.</p><div class="topic-grid"><span class="topic">HTTP, TCP/UDP, DNS, WebSockets and gRPC</span><span class="topic">Load balancers, gateways and stateless services</span><span class="topic">Redis, cache-aside, TTL, invalidation and stampede</span><span class="topic">SQL/NoSQL, indexes, replication and sharding</span><span class="topic">Kafka, queues, pub/sub, workers and backpressure</span><span class="topic">CDNs, object storage and media delivery</span></div></div></details>
        <details class="phase"><summary><span class="phase-no">03</span><span class="phase-title"><b>Distributed reality</b><span>consistency · failure · concurrency · reliability · operations</span></span></summary><div class="phase-content"><p>Move beyond diagrams into the problems production systems actually have.</p><div class="topic-grid"><span class="topic">CAP, consistency models and replication lag</span><span class="topic">Quorums, leader election and consensus intuition</span><span class="topic">Retries, timeouts, circuit breakers and bulkheads</span><span class="topic">Idempotency, duplicate delivery and saga workflows</span><span class="topic">Hot keys, partitions, skew and rate limiting</span><span class="topic">Metrics, logs, traces, SLIs/SLOs and recovery</span></div></div></details>
        <details class="phase"><summary><span class="phase-no">04</span><span class="phase-title"><b>Classic architecture labs</b><span>feeds · chat · booking · payments · video · collaboration</span></span></summary><div class="phase-content"><p>Apply the same interview framework repeatedly until it becomes automatic.</p><div class="topic-grid"><span class="topic">URL shortener + rate limiter</span><span class="topic">Chat, presence and notifications</span><span class="topic">News feed and fan-out</span><span class="topic">Ticket booking and concurrency</span><span class="topic">Payments and idempotent workflows</span><span class="topic">File sync, video streaming and nearby search</span></div></div></details>
        <details class="phase"><summary><span class="phase-no">05</span><span class="phase-title"><b>AI becomes a backend dependency</b><span>models · gateways · context · routing · cost · fallbacks</span></span></summary><div class="phase-content"><p>Understand why an LLM behaves differently from a normal service dependency.</p><div class="topic-grid"><span class="topic">Tokens, context windows and streaming</span><span class="topic">Structured output and tool calling</span><span class="topic">AI gateways, provider routing and fallback</span><span class="topic">Token-based rate limits and cost budgets</span><span class="topic">Prompt/context versioning and state</span><span class="topic">Semantic caching and graceful degradation</span></div></div></details>
        <details class="phase"><summary><span class="phase-no">06</span><span class="phase-title"><b>Production RAG & semantic search</b><span>ingestion · embeddings · vector indexes · reranking · permissions</span></span></summary><div class="phase-content"><p>Go far beyond “vector DB + LLM”. Design the complete information pipeline.</p><div class="topic-grid"><span class="topic">Parsing, chunking and embedding pipelines</span><span class="topic">HNSW and ANN intuition</span><span class="topic">Vector vs lexical vs hybrid retrieval</span><span class="topic">Reranking and context assembly</span><span class="topic">Freshness, access control and multitenancy</span><span class="topic">RAG quality, latency and failure modes</span></div></div></details>
        <details class="phase"><summary><span class="phase-no">07</span><span class="phase-title"><b>Agents meet microservices</b><span>tools · MCP · memory · workflows · safety · durability</span></span></summary><div class="phase-content"><p>Keep deterministic services deterministic; let the agent operate through controlled interfaces.</p><div class="topic-grid"><span class="topic">Workflow vs agent: when not to use autonomy</span><span class="topic">Tool schemas, registries and discovery</span><span class="topic">Short-term memory, long-term memory and checkpoints</span><span class="topic">Retries, idempotent tool calls and durable execution</span><span class="topic">MCP architecture and service integration</span><span class="topic">Human approval, permissions and agent budgets</span></div></div></details>
        <details class="phase"><summary><span class="phase-no">08</span><span class="phase-title"><b>Production AI reliability</b><span>evals · tracing · security · cost · observability</span></span></summary><div class="phase-content"><p>The chapter that turns an AI demo into an operable production system.</p><div class="topic-grid"><span class="topic">Golden sets, offline/online evals and regression tests</span><span class="topic">Prompt, retrieval and tool-call tracing</span><span class="topic">Hallucination and quality failure handling</span><span class="topic">Prompt injection and poisoned retrieval</span><span class="topic">Cost-per-request, routing and caching</span><span class="topic">Provider outages, queues and degradation</span></div></div></details>
        <details class="phase"><summary><span class="phase-no">09</span><span class="phase-title"><b>Realtime voice architecture</b><span>WebRTC · streaming · interruption · latency · sessions</span></span></summary><div class="phase-content"><p>Use CodesBlock's own voice tutor as a system-design case study.</p><div class="topic-grid"><span class="topic">STT → LLM → TTS vs speech-to-speech</span><span class="topic">WebRTC and WebSockets</span><span class="topic">Voice activity detection and barge-in</span><span class="topic">Conversation/session state</span><span class="topic">Tool use during voice conversations</span><span class="topic">Latency budgets and concurrent-call scaling</span></div></div></details>
        <details class="phase"><summary><span class="phase-no">10</span><span class="phase-title"><b>Pressure test & capstone</b><span>8 mocks · constraint ladders · architecture report · review path</span></span></summary><div class="phase-content"><p>Finish by designing systems from a blank canvas and defending them under changing requirements.</p><div class="topic-grid"><span class="topic">Classic architecture mock</span><span class="topic">Senior reliability mock</span><span class="topic">RAG architecture mock</span><span class="topic">Agent architecture mock</span><span class="topic">Voice architecture mock</span><span class="topic">Capstone: design, break and defend</span></div></div></details>
      </div>
      <aside class="side" id="start"><div class="eyebrow">Start free</div><h3>See the course before you commit.</h3><p>Open the first lessons, use the learning workspace and decide whether the teaching style works for you.</p><div class="side-list"><span><i>✓</i>90+ guided lessons</span><span><i>✓</i>18 architecture labs</span><span><i>✓</i>Voice AI tutor in-context</span><span><i>✓</i>Highlights, notes and bookmarks</span><span><i>✓</i>8 adaptive AI mocks</span></div><a class="btn primary" href="#">Sign in to start →</a><small>No payment required to begin</small></aside>
    </div>
  </div>
</section>

<section class="surface" id="labs">
  <div class="wrap">
    <div class="section-head"><div class="kicker">Architecture labs</div><h2>Design systems where one changed assumption <span class="accent">changes the answer.</span></h2><p>Classic questions establish the fundamentals. Modern labs then add retrieval, models, agents, realtime media and AI-specific failure modes.</p></div>
    <div class="labs"><article class="lab"><div class="meta">Lab 04 · Scale</div><h3>Design a high-traffic feed</h3><p>Fan-out, hot users, ranking, pagination, caching and eventual consistency.</p><div class="labflow"><span>Post</span><i>→</i><span>Fan-out</span><i>→</i><span>Feed cache</span><i>→</i><span>User</span></div></article><article class="lab"><div class="meta">Lab 07 · Reliability</div><h3>Design payment processing</h3><p>Idempotency, ledgers, webhooks, reconciliation and partial failure recovery.</p><div class="labflow"><span>Pay</span><i>→</i><span>Ledger</span><i>→</i><span>PSP</span><i>→</i><span>Reconcile</span></div></article><article class="lab"><div class="meta">Lab 11 · Retrieval</div><h3>Design enterprise RAG</h3><p>Permissions, ingestion freshness, hybrid retrieval, reranking and citations.</p><div class="labflow"><span>Docs</span><i>→</i><span>Index</span><i>→</i><span>Retrieve</span><i>→</i><span>Answer</span></div></article><article class="lab"><div class="meta">Lab 13 · Platform</div><h3>Design an AI gateway</h3><p>Provider abstraction, routing, token limits, fallback, cost and observability.</p><div class="labflow"><span>App</span><i>→</i><span>Gateway</span><i>→</i><span>Router</span><i>→</i><span>Models</span></div></article><article class="lab"><div class="meta">Lab 16 · Agents</div><h3>Design a coding agent</h3><p>Repo indexing, tool execution, sandboxes, task state, human review and evals.</p><div class="labflow"><span>Repo</span><i>→</i><span>Agent</span><i>→</i><span>Tools</span><i>→</i><span>Sandbox</span></div></article><article class="lab"><div class="meta">Lab 18 · Realtime</div><h3>Design a voice AI interviewer</h3><p>Streaming media, interruptions, session memory, model latency and scoring.</p><div class="labflow"><span>Voice</span><i>→</i><span>Realtime</span><i>→</i><span>Tools</span><i>→</i><span>Report</span></div></article></div>
  </div>
</section>

<section class="tutor-section" id="tutor">
  <div class="wrap tutor-grid">
    <div><div class="kicker">Built into the lesson</div><div class="section-head" style="margin-bottom:0"><h2>Your AI tutor should help you think—not replace the thinking.</h2><p>Read first. Form an answer. Then use AI at the exact point you get stuck, without leaving the course.</p></div><div class="feature-list"><div class="f"><i>01</i><div><b>Highlight → ask</b><p>Select a sentence or trade-off and explain it in context.</p></div></div><div class="f"><i>02</i><div><b>Talk instead of type</b><p>Use voice to ask follow-ups while you work through the architecture.</p></div></div><div class="f"><i>03</i><div><b>Save useful thinking</b><p>Turn highlights into bookmarks, notes and revision prompts.</p></div></div><div class="f"><i>04</i><div><b>Ask the tutor to attack your answer</b><p>Generate interviewer follow-ups instead of simply revealing the solution.</p></div></div></div></div>
    <div class="product-board"><div class="board-head"><span>course / ai-gateway / lesson 04</span><span>68% complete</span></div><div class="board"><div class="reading"><h4>Fallback without cascading failure</h4><p>If the primary model exceeds its latency budget, the gateway can route to a smaller fallback model. <span class="selection">But a fallback that receives the same traffic spike can fail for the same reason.</span></p><div class="pop"><span>Ask AI</span><span>Explain</span><span>Bookmark</span></div><div class="arch" style="margin-top:13px"><div class="flow"><span class="node">API</span><span class="arrow">→</span><span class="node ai">Gateway</span><span class="arrow">→</span><span class="node">Primary</span><span class="node">Fallback</span></div></div></div><div class="assistant"><small>AI tutor · selected text</small><p>A fallback is useful only if it has independent capacity or a different failure profile. Otherwise it can turn one overloaded dependency into two.</p><div class="voicebox">● Ask with voice</div><div class="bookmark">Saved note: fallback isolation + separate quota</div></div></div></div>
  </div>
</section>

<section>
  <div class="wrap">
    <div class="section-head center"><div class="kicker">What you leave with</div><h2>Not a folder of diagrams. A <span class="accent">repeatable way to reason.</span></h2></div>
    <div class="outcome"><article class="outcome-card"><h3>Interview readiness</h3><ul><li>Turn vague prompts into a structured 45-minute conversation.</li><li>Estimate scale before selecting infrastructure.</li><li>Explain database, caching, messaging and consistency trade-offs.</li><li>Handle “what if?” follow-ups without freezing.</li><li>Communicate an architecture at junior, mid and senior depth.</li></ul></article><article class="outcome-card emphasis"><h3>Modern architecture literacy</h3><ul><li>Recognize when RAG is useful—and when it is not.</li><li>Reason about vector retrieval, reranking and permissions.</li><li>Integrate models behind reliable backend services.</li><li>Design bounded agents that safely call microservices.</li><li>Discuss AI cost, evals, security, tracing and graceful degradation.</li></ul></article></div>
  </div>
</section>

<section class="final">
  <div class="wrap final-card"><div><div class="kicker" style="color:#8fc2ff">Crack the interview. Build the system.</div><h2>Learn the old rules. Then learn what changed.</h2><p>From databases, Redis, Kafka and microservices to RAG, model gateways, agents and realtime voice—build the architectural judgment to explain, adapt and defend your design.</p></div><div class="final-actions"><a class="btn darkbtn btn-lg" href="#">Start learning free →</a><a class="btn ghost-dark btn-lg" href="#curriculum">Review curriculum</a><small>No card required to start</small></div></div>
</section>
</main>

<?php
get_footer( 'landing' );
