<?php
/**
 * Landing page header.
 */
?>
<!doctype html>
<html <?php language_attributes(); ?>>
<head>
<meta charset="<?php bloginfo( 'charset' ); ?>" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Crack the System Design Interview — CodesBlock</title>
<meta name="description" content="Learn classic distributed system design and the architecture behind modern AI products: RAG, vector search, AI gateways, agents, MCP, realtime voice, reliability, cost and evaluation." />
<?php wp_head(); ?>
<style>
:root{
  --bg:#f7f7f3;--surface:#fff;--ink:#111820;--muted:#5e6975;--line:#dde3e7;
  --blue:#1768d5;--blue2:#0e4ea8;--navy:#111a23;--soft-blue:#edf5ff;
  --yellow:#f4d15a;--green:#dff2e8;--orange:#fff1d6;--red:#ffe8e5;
  --max:1180px;--radius:18px;--shadow:0 18px 48px rgba(17,24,32,.08);
}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--bg);color:var(--ink);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;line-height:1.55;-webkit-font-smoothing:antialiased}a{text-decoration:none;color:inherit}button{font:inherit}.wrap{width:min(var(--max),calc(100% - 40px));margin-inline:auto}.tiny{font-size:12px;color:var(--muted)}
.promo{background:var(--navy);color:#fff;text-align:center;padding:8px 16px;font-size:12px}.promo b{color:var(--yellow)}
header{position:sticky;top:0;z-index:50;background:rgba(247,247,243,.94);backdrop-filter:blur(14px);border-bottom:1px solid rgba(17,24,32,.08)}.nav{height:66px;display:flex;align-items:center;gap:26px}.brand{display:flex;align-items:center;gap:9px;font-weight:850;letter-spacing:-.02em}.mark{width:36px;height:36px;border:1px solid var(--line);border-radius:10px;background:#fff;display:grid;place-items:center;font-weight:900}.mark span{color:var(--blue)}.navlinks{display:flex;gap:22px;font-size:13px;color:#48535e}.navlinks a:hover{color:#111}.actions{margin-left:auto;display:flex;gap:9px}.btn{display:inline-flex;align-items:center;justify-content:center;gap:8px;padding:11px 16px;border:1px solid var(--line);border-radius:10px;background:#fff;color:var(--ink);font-size:13px;font-weight:750;cursor:pointer}.btn:hover{border-color:#bfc9d1}.primary{background:var(--blue);border-color:var(--blue);color:#fff;box-shadow:0 8px 18px rgba(23,104,213,.16)}.primary:hover{background:var(--blue2)}.btn-lg{padding:14px 20px;font-size:14px}.darkbtn{background:#fff;color:#111;border-color:#fff}.ghost-dark{background:transparent;color:#fff;border-color:#34414d}
.eyebrow{display:inline-flex;align-items:center;gap:7px;font-size:11px;font-weight:850;text-transform:uppercase;letter-spacing:.09em;color:#3f5b72}.eyebrow:before{content:"";width:7px;height:7px;border-radius:50%;background:var(--blue)}
.hero{padding:70px 0 42px}.hero-grid{display:grid;grid-template-columns:1.04fr .96fr;gap:58px;align-items:center}.hero h1{font-size:clamp(46px,6vw,76px);line-height:.98;letter-spacing:-.058em;margin:18px 0 20px;max-width:760px}.hero h1 span{color:var(--blue)}.hero .lead{font-size:19px;color:#49545f;max-width:700px;margin:0 0 22px}.hero .lead strong{color:var(--ink)}.hero .promise{font-size:15px;font-weight:780;max-width:700px;border-left:3px solid var(--yellow);padding-left:14px;margin:22px 0;color:#27313b}.hero-cta{display:flex;gap:10px;flex-wrap:wrap;margin-top:26px}.micro{display:flex;gap:16px;flex-wrap:wrap;margin-top:14px;font-size:12px;color:var(--muted)}.micro span{display:flex;gap:6px;align-items:center}.tick{width:16px;height:16px;border-radius:50%;background:var(--green);display:grid;place-items:center;font-size:10px;font-weight:900}
.course-window{background:#fff;border:1px solid var(--line);border-radius:22px;overflow:hidden;box-shadow:var(--shadow)}.windowtop{height:42px;border-bottom:1px solid var(--line);display:flex;align-items:center;padding:0 14px;gap:6px;background:#fafbf9}.windowtop i{width:8px;height:8px;border-radius:50%;background:#c9cfd4}.windowtop small{margin-left:8px;color:#7a838c}.demo{display:grid;grid-template-columns:1.23fr .77fr;min-height:470px}.lesson{padding:24px}.lesson small{font-weight:800;color:#6f7b86;text-transform:uppercase;letter-spacing:.08em;font-size:9px}.lesson h3{font-size:22px;line-height:1.17;margin:8px 0 12px}.lesson p{font-size:13px;color:#4c5863}.highlight{background:linear-gradient(transparent 56%,rgba(244,209,90,.66) 56%)}.toolrow{display:flex;gap:6px;flex-wrap:wrap;margin:13px 0}.tool{font-size:10px;font-weight:750;padding:7px 8px;border:1px solid var(--line);border-radius:7px;background:#fff}.tool.on{background:var(--soft-blue);border-color:#b6d2f7;color:#0f55b3}.arch{margin-top:18px;background:#f6f8fa;border:1px solid #e1e6ea;border-radius:13px;padding:15px}.flow{display:flex;align-items:center;justify-content:center;gap:6px;flex-wrap:wrap}.node{padding:7px 8px;border:1px solid #ccd5dc;border-radius:7px;background:#fff;font-size:9px;font-weight:800}.node.ai{background:#edf5ff;border-color:#a9c9f3}.arrow{font-size:11px;color:#8794a0}.tutor{background:#111a23;color:#fff;padding:18px;display:flex;flex-direction:column}.tutor-head{display:flex;justify-content:space-between;align-items:center;font-size:12px;font-weight:800}.orb{width:23px;height:23px;border-radius:7px;background:linear-gradient(135deg,#6cb0ff,#f3d05b);display:inline-block;vertical-align:middle;margin-right:7px}.voice-tag{font-size:9px;color:#cdd6dd;border:1px solid #35434e;padding:5px 7px;border-radius:99px}.chat{margin-top:18px;background:#192630;border:1px solid #2d3b47;border-radius:12px;padding:12px}.chat small{color:#93a4b2;font-size:9px}.chat p{font-size:11px;color:#e7edf2;margin:6px 0 0}.wave{height:45px;display:flex;align-items:center;justify-content:center;gap:3px;margin:14px 0}.wave i{width:3px;background:#7eb6ff;border-radius:4px}.wave i:nth-child(1){height:9px}.wave i:nth-child(2){height:17px}.wave i:nth-child(3){height:29px}.wave i:nth-child(4){height:18px}.wave i:nth-child(5){height:36px}.wave i:nth-child(6){height:24px}.wave i:nth-child(7){height:14px}.wave i:nth-child(8){height:31px}.talk{margin-top:auto;background:#fff;color:#111;border-radius:9px;padding:10px;text-align:center;font-size:10px;font-weight:850}.hero-stats{display:grid;grid-template-columns:repeat(4,1fr);margin-top:28px;border-top:1px solid var(--line);border-bottom:1px solid var(--line)}.hero-stats div{padding:15px 14px 15px 0}.hero-stats div+div{padding-left:15px;border-left:1px solid var(--line)}.hero-stats b{display:block;font-size:16px}.hero-stats span{font-size:11px;color:var(--muted)}
.anchor{padding:14px 0 0}.anchor-inner{display:flex;gap:7px;flex-wrap:wrap}.anchor a{font-size:11px;background:#fff;border:1px solid var(--line);border-radius:8px;padding:7px 10px;color:#53606b}
section{padding:82px 0}.surface{background:#fff;border-top:1px solid var(--line);border-bottom:1px solid var(--line)}.section-head{max-width:780px;margin-bottom:34px}.section-head.center{text-align:center;margin-inline:auto}.kicker{font-size:11px;font-weight:850;letter-spacing:.09em;text-transform:uppercase;color:var(--blue);margin-bottom:10px}.section-head h2{font-size:clamp(33px,4.6vw,54px);line-height:1.04;letter-spacing:-.047em;margin:0 0 14px}.section-head p{font-size:16px;color:var(--muted);margin:0}.accent{color:var(--blue)}
.split-story{display:grid;grid-template-columns:1fr 1fr;gap:18px}.story-card{border:1px solid var(--line);border-radius:18px;background:#fff;padding:26px}.story-card.dark{background:var(--navy);color:#fff;border-color:var(--navy)}.story-card .label{font-size:10px;text-transform:uppercase;letter-spacing:.09em;font-weight:850;color:#74818d}.story-card.dark .label{color:#9fb0bd}.story-card h3{font-size:24px;letter-spacing:-.025em;margin:11px 0 16px}.stack{display:flex;gap:7px;flex-wrap:wrap}.stack span{font-size:11px;padding:7px 9px;border-radius:8px;border:1px solid var(--line);background:#f7f8f9;font-weight:700}.story-card.dark .stack span{background:#1d2a35;border-color:#34424e;color:#dfe7ed}.bridge{grid-column:1/-1;background:#f1f5f8;border:1px solid #dce4e9;border-radius:18px;padding:26px 28px;display:grid;grid-template-columns:1.35fr .65fr;gap:24px;align-items:center}.bridge blockquote{font-size:clamp(22px,3vw,34px);line-height:1.18;letter-spacing:-.035em;margin:0;font-weight:780}.bridge blockquote span{color:var(--blue)}.bridge p{font-size:13px;color:var(--muted);margin:0}
.compare{display:grid;grid-template-columns:repeat(5,1fr);gap:10px}.compare .col{background:#fff;border:1px solid var(--line);border-radius:14px;padding:17px;min-height:165px}.compare .n{font-size:10px;font-weight:900;color:#82909b}.compare strong{display:block;color:var(--blue);font-size:28px;margin:9px 0 4px}.compare b{font-size:13px}.compare p{font-size:11px;color:var(--muted);margin:7px 0 0}
.method-grid{display:grid;grid-template-columns:1.05fr .95fr;gap:22px;align-items:stretch}.method-card{border:1px solid var(--line);border-radius:18px;background:#fff;padding:25px}.method-card h3{font-size:22px;margin:0 0 8px}.method-card p{font-size:13px;color:var(--muted);margin:0}.evolve{margin-top:20px;display:grid;gap:10px}.evolve-row{display:grid;grid-template-columns:120px 1fr;gap:12px;align-items:center}.evolve-row small{font-size:10px;font-weight:850;color:#6c7882;text-transform:uppercase}.evolve-path{display:flex;align-items:center;gap:6px;flex-wrap:wrap}.evolve-path span{font-size:10px;font-weight:750;border:1px solid #d4dce2;border-radius:7px;background:#f8fafb;padding:7px 8px}.evolve-path .new{background:#edf5ff;border-color:#b9d4f7;color:#0c55b5}.pressure{background:var(--navy);color:#fff}.pressure p{color:#aebbc5}.pressure .question{margin-top:18px;border:1px solid #33424e;background:#18252f;border-radius:12px;padding:13px}.question small{color:#8fa2b1;text-transform:uppercase;font-size:9px;letter-spacing:.08em;font-weight:850}.question p{color:#edf3f7;margin:5px 0 0;font-size:13px}.score{margin-top:16px;display:grid;gap:9px}.score-row{display:grid;grid-template-columns:90px 1fr 28px;gap:8px;align-items:center;font-size:10px}.score-row i{height:6px;background:#2e3d49;border-radius:99px;overflow:hidden}.score-row i span{display:block;height:100%;background:#79b4ff}.score-row b{text-align:right;font-size:10px}
.ai-era{background:var(--navy);color:#fff}.ai-era .section-head p{color:#aebbc5}.ai-era .kicker{color:#85bbff}.ai-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.ai-card{background:#17232d;border:1px solid #2c3a46;border-radius:16px;padding:21px}.ai-card .tag{display:inline-flex;font-size:9px;font-weight:900;letter-spacing:.07em;padding:5px 7px;border-radius:6px;background:#21394e;color:#9ec9ff}.ai-card h3{font-size:18px;margin:13px 0 7px}.ai-card p{font-size:12px;color:#adbac4;margin:0}.mini-flow{margin-top:16px;display:flex;align-items:center;gap:5px;flex-wrap:wrap}.mini-flow span{font-size:9px;padding:5px 6px;border-radius:6px;border:1px solid #364653;background:#111a23}.mini-flow i{font-style:normal;color:#7690a4;font-size:9px}
.curriculum-layout{display:grid;grid-template-columns:minmax(0,1fr) 300px;gap:28px;align-items:start}.phases{display:grid;gap:10px}.phase{border:1px solid var(--line);background:#fff;border-radius:14px;overflow:hidden}.phase summary{list-style:none;cursor:pointer;padding:18px;display:grid;grid-template-columns:34px 1fr 20px;gap:11px;align-items:start}.phase summary::-webkit-details-marker{display:none}.phase-no{font-size:10px;font-weight:900;color:#7a8792;padding-top:4px}.phase-title b{font-size:15px}.phase-title span{display:block;font-size:11px;color:var(--muted);margin-top:4px}.phase summary:after{content:"+";font-size:18px;color:#80909c}.phase[open] summary:after{content:"–"}.phase-content{border-top:1px solid var(--line);padding:18px 18px 20px 63px}.phase-content p{font-size:12px;color:var(--muted);margin:0 0 14px}.topic-grid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.topic{background:#f7f9fa;border:1px solid #e3e8eb;border-radius:7px;padding:8px;font-size:10px}.side{position:sticky;top:92px;border:1px solid var(--line);background:#fff;border-radius:17px;padding:21px;box-shadow:0 12px 32px rgba(16,24,32,.05)}.side h3{font-size:21px;margin:7px 0}.side p{font-size:12px;color:var(--muted)}.side-list{display:grid;gap:9px;margin:18px 0}.side-list span{font-size:11px;display:flex;gap:7px;align-items:start}.side-list i{font-style:normal;color:#187547}.side .btn{width:100%}.side small{display:block;text-align:center;color:var(--muted);margin-top:8px;font-size:9px}
.labs{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.lab{border:1px solid var(--line);background:#fff;border-radius:16px;padding:20px}.lab .meta{font-size:9px;text-transform:uppercase;letter-spacing:.08em;font-weight:900;color:#6f7d88}.lab h3{font-size:18px;margin:10px 0 7px}.lab p{font-size:12px;color:var(--muted);margin:0}.labflow{margin-top:15px;display:flex;gap:5px;align-items:center;flex-wrap:wrap}.labflow span{font-size:9px;border:1px solid #d8e0e5;background:#f7f9fa;border-radius:6px;padding:5px 6px}.labflow i{font-style:normal;color:#85939e;font-size:9px}
.tutor-section{background:#fff;border-top:1px solid var(--line);border-bottom:1px solid var(--line)}.tutor-grid{display:grid;grid-template-columns:.8fr 1.2fr;gap:38px;align-items:center}.feature-list{display:grid;gap:13px;margin-top:24px}.f{display:grid;grid-template-columns:30px 1fr;gap:10px}.f i{width:27px;height:27px;border-radius:8px;background:#edf4fb;display:grid;place-items:center;font-style:normal;font-size:10px;font-weight:900;color:#0f5aba}.f b{font-size:13px}.f p{font-size:11px;color:var(--muted);margin:3px 0 0}.product-board{border:1px solid var(--line);border-radius:19px;background:#f6f8f9;padding:17px;box-shadow:var(--shadow)}.board-head{display:flex;justify-content:space-between;font-size:10px;color:#6c7984;margin-bottom:12px}.board{display:grid;grid-template-columns:1fr .72fr;gap:11px}.reading,.assistant{border:1px solid #dbe2e6;border-radius:12px;background:#fff;padding:15px}.reading h4{margin:0 0 8px;font-size:15px}.reading p{font-size:10px;color:#53616c}.selection{background:#fff2b5;padding:1px 2px}.pop{display:inline-flex;gap:4px;border:1px solid #d8e0e5;border-radius:7px;padding:5px;background:#fff}.pop span{font-size:8px;font-weight:800;padding:3px 4px}.assistant{background:#121b24;color:#fff;border-color:#121b24}.assistant small{color:#94a5b3;font-size:8px}.assistant p{font-size:10px;color:#e6edf2}.assistant .voicebox{margin-top:10px;border:1px solid #32414c;background:#19252f;border-radius:9px;padding:9px;text-align:center;font-size:9px}.bookmark{margin-top:9px;border-top:1px solid #32414c;padding-top:9px;color:#abb9c4;font-size:8px}
.outcome{display:grid;grid-template-columns:1fr 1fr;gap:18px}.outcome-card{border:1px solid var(--line);background:#fff;border-radius:17px;padding:24px}.outcome-card h3{font-size:21px;margin:0 0 13px}.outcome-card ul{padding:0;margin:0;list-style:none;display:grid;gap:9px}.outcome-card li{font-size:12px;color:#4e5b66;display:flex;gap:8px}.outcome-card li:before{content:"✓";color:#187548;font-weight:900}.outcome-card.emphasis{background:#edf5ff;border-color:#c8dcf5}.outcome-card.emphasis li:before{color:#0d5bbd}
.final{padding:92px 0}.final-card{background:var(--navy);color:#fff;border-radius:23px;padding:48px;display:grid;grid-template-columns:1.2fr .8fr;gap:34px;align-items:center}.final-card h2{font-size:clamp(34px,4.5vw,54px);line-height:1.02;letter-spacing:-.045em;margin:0 0 14px}.final-card p{color:#b6c2cb;margin:0;max-width:650px}.final-actions{display:flex;flex-direction:column;gap:9px}.final-actions small{text-align:center;color:#8fa1ae;font-size:9px}
footer{border-top:1px solid var(--line);padding:28px 0 38px;color:#6a7680;font-size:11px}.foot{display:flex;justify-content:space-between;gap:16px}.sticky-mobile{display:none}
@media(max-width:980px){.navlinks{display:none}.hero-grid,.method-grid,.tutor-grid{grid-template-columns:1fr}.hero-grid{gap:34px}.hero h1{max-width:850px}.course-window{max-width:720px}.compare{grid-template-columns:repeat(3,1fr)}.ai-grid,.labs{grid-template-columns:repeat(2,1fr)}.curriculum-layout{grid-template-columns:1fr}.side{position:static}.final-card{grid-template-columns:1fr}.bridge{grid-template-columns:1fr}}
@media(max-width:680px){.wrap{width:min(100% - 26px,var(--max))}.promo{font-size:10px}.actions .btn:first-child{display:none}.hero{padding-top:45px}.hero h1{font-size:48px}.hero .lead{font-size:16px}.hero-stats{grid-template-columns:1fr 1fr}.hero-stats div:nth-child(3){border-left:0;padding-left:0}.demo{grid-template-columns:1fr}.tutor{min-height:290px}.split-story,.outcome{grid-template-columns:1fr}.bridge{grid-column:auto}.compare{grid-template-columns:1fr}.ai-grid,.labs{grid-template-columns:1fr}.topic-grid{grid-template-columns:1fr}.phase-content{padding-left:18px}.board{grid-template-columns:1fr}.final-card{padding:30px 22px}.final{padding-bottom:95px}.sticky-mobile{display:flex;position:fixed;z-index:80;left:10px;right:10px;bottom:10px;border:1px solid #cbd5dc;background:rgba(255,255,255,.96);backdrop-filter:blur(12px);border-radius:13px;padding:8px;box-shadow:0 14px 38px rgba(0,0,0,.16);align-items:center;gap:10px}.sticky-mobile div{flex:1;padding-left:4px}.sticky-mobile b{display:block;font-size:11px}.sticky-mobile span{font-size:9px;color:var(--muted)}.sticky-mobile .btn{padding:10px 12px}}
</style>
</head>
<body <?php body_class(); ?>>
<?php wp_body_open(); ?>
<div class="promo"><b>25% off</b> your first Pro month with WELCOME25</div>
<header><div class="wrap nav"><a class="brand" href="<?php echo esc_url( home_url( '/' ) ); ?>"><div class="mark">C<span>B</span></div>CodesBlock</a><nav class="navlinks"><a href="<?php echo esc_url( home_url( '/' ) ); ?>">Home</a><a href="#">Articles</a><a href="#">Courses</a><a href="#">Interview Guides</a><a href="#">Start Here</a></nav><div class="actions"><a class="btn" href="#">Sign in</a><a class="btn primary" href="#start">Start course →</a></div></div></header>
